apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: toy-load
  namespace: default
  labels:
    app: toy-load
spec:
  selector:
    matchLabels:
      app: toy-load
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
