version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/toy-load"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/analysis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/toy-load"
    schedule:
      interval: "weekly"
