{{- if and .Values.prometheusOperator.enabled .Values.prometheusOperator.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "toy-load.fullname" . }}
  namespace: {{ default (include "toy-load.namespace" .) .Values.prometheusOperator.podMonitor.namespace }}
  labels:
    {{- include "toy-load.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "toy-load.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "toy-load.namespace" . }}
  podMetricsEndpoints:
    - port: http
      path: {{ .Values.config.metricsPath }}
      interval: {{ .Values.prometheusOperator.podMonitor.interval }}
{{- end }}
