replicaCount: 2

image:
  repository: ghcr.io/vshulcz/toy-load
  tag: ecba019
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 9090

config:
  port: 9090
  metricsPath: /metrics
  readTimeout: 5s
  writeTimeout: 10s
  idleTimeout: 60s
  maxHeaderBytes: 1048576
  logLevel: info
  appName: toy-load

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

livenessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2

readinessProbe:
  path: /readyz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2

nodeSelector: {}
tolerations: []
affinity: {}

prometheusOperator:
  enabled: true
  serviceMonitor:
    interval: 30s
    scrapeTimeout: 10s
    namespace: ""
  podMonitor:
    enabled: false
    interval: 30s
    namespace: ""

dashboard:
  enabled: true
  namespace: ""

rbac:
  create: false
