apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toy-monitoring
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: toy-monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.1.1
    helm:
      releaseName: toy-monitoring
      values: |
        grafana:
          enabled: true
          defaultDashboardsEnabled: true
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              searchNamespace: ALL

        prometheus:
          enabled: true
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            podMonitorNamespaceSelector: {}

        alertmanager:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
