apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toy-load
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/vshulcz/mpc-autoscaler.git
    targetRevision: main
    path: deploy/helm/toy-load
    helm:
      releaseName: toy-load
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
