apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: toy-load
  labels:
    app.kubernetes.io/name: toy-load-servicemonitor
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: toy-load
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
      scheme: http
