apiVersion: v1
kind: Service
metadata:
  name: {{ include "toy-load.fullname" . }}
  namespace: {{ include "toy-load.namespace" . }}
  labels:
    {{- include "toy-load.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "toy-load.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
